spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yomankum?useSSL=false&allowPublicKeyRetrieval=true
    username: holiday
    password: in828282

  security:
    oauth2:
      client:
        registration:
          google: # 도메인 없어서 불가
            client-id: cliendtId
            client-secret: cliendtSecret
            scope:
              - email
            redirect-uri: http://localhost:8080/
          naver:
            client-id: VVrviPtw50xif3PUsvby
            client-secret: HmOv7ewoJF
            scope:
              - name
              - email
              - mobile
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/
          kakao:
            client-id: de846ae383b9c41af8d14bcc90700379
            client-secret: L8HQwlujw5evIjkGe0wTgYLILXXAQG7z
            scope:
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/
            client-authentication-method: POST

  mail:
    host: smtp.naver.com
    port: 465
    username: y0mankum
    password: yomankum1004
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
  redis:
    host: cube.3trolls.me
    port: 16379
    password: 16379

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    algorithm: PBEWithMD5AndDES
    ivGeneratorClassname: org.jasypt.iv.NoIvGenerator